// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package hellopb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PK_HELLO_REQ_CMD_HELLO_REQ int32

const (
	PK_HELLO_REQ_UNKNOWN PK_HELLO_REQ_CMD_HELLO_REQ = 0
	PK_HELLO_REQ_CMD     PK_HELLO_REQ_CMD_HELLO_REQ = 168493057
)

var PK_HELLO_REQ_CMD_HELLO_REQ_name = map[int32]string{
	0:         "UNKNOWN",
	168493057: "CMD",
}

var PK_HELLO_REQ_CMD_HELLO_REQ_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     168493057,
}

func (x PK_HELLO_REQ_CMD_HELLO_REQ) String() string {
	return proto.EnumName(PK_HELLO_REQ_CMD_HELLO_REQ_name, int32(x))
}

func (PK_HELLO_REQ_CMD_HELLO_REQ) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0, 0}
}

type PK_HELLO_RSP_CMD_HELLO_RSP int32

const (
	PK_HELLO_RSP_UNKNOWN PK_HELLO_RSP_CMD_HELLO_RSP = 0
	PK_HELLO_RSP_CMD     PK_HELLO_RSP_CMD_HELLO_RSP = 185204737
)

var PK_HELLO_RSP_CMD_HELLO_RSP_name = map[int32]string{
	0:         "UNKNOWN",
	185204737: "CMD",
}

var PK_HELLO_RSP_CMD_HELLO_RSP_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     185204737,
}

func (x PK_HELLO_RSP_CMD_HELLO_RSP) String() string {
	return proto.EnumName(PK_HELLO_RSP_CMD_HELLO_RSP_name, int32(x))
}

func (PK_HELLO_RSP_CMD_HELLO_RSP) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1, 0}
}

type PK_HELLO_REQ struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_HELLO_REQ) Reset()         { *m = PK_HELLO_REQ{} }
func (m *PK_HELLO_REQ) String() string { return proto.CompactTextString(m) }
func (*PK_HELLO_REQ) ProtoMessage()    {}
func (*PK_HELLO_REQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}

func (m *PK_HELLO_REQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_HELLO_REQ.Unmarshal(m, b)
}
func (m *PK_HELLO_REQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_HELLO_REQ.Marshal(b, m, deterministic)
}
func (m *PK_HELLO_REQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_HELLO_REQ.Merge(m, src)
}
func (m *PK_HELLO_REQ) XXX_Size() int {
	return xxx_messageInfo_PK_HELLO_REQ.Size(m)
}
func (m *PK_HELLO_REQ) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_HELLO_REQ.DiscardUnknown(m)
}

var xxx_messageInfo_PK_HELLO_REQ proto.InternalMessageInfo

func (m *PK_HELLO_REQ) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PK_HELLO_RSP struct {
	Errmsg               string   `protobuf:"bytes,1,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_HELLO_RSP) Reset()         { *m = PK_HELLO_RSP{} }
func (m *PK_HELLO_RSP) String() string { return proto.CompactTextString(m) }
func (*PK_HELLO_RSP) ProtoMessage()    {}
func (*PK_HELLO_RSP) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1}
}

func (m *PK_HELLO_RSP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_HELLO_RSP.Unmarshal(m, b)
}
func (m *PK_HELLO_RSP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_HELLO_RSP.Marshal(b, m, deterministic)
}
func (m *PK_HELLO_RSP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_HELLO_RSP.Merge(m, src)
}
func (m *PK_HELLO_RSP) XXX_Size() int {
	return xxx_messageInfo_PK_HELLO_RSP.Size(m)
}
func (m *PK_HELLO_RSP) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_HELLO_RSP.DiscardUnknown(m)
}

var xxx_messageInfo_PK_HELLO_RSP proto.InternalMessageInfo

func (m *PK_HELLO_RSP) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func init() {
	proto.RegisterEnum("hellopb.PK_HELLO_REQ_CMD_HELLO_REQ", PK_HELLO_REQ_CMD_HELLO_REQ_name, PK_HELLO_REQ_CMD_HELLO_REQ_value)
	proto.RegisterEnum("hellopb.PK_HELLO_RSP_CMD_HELLO_RSP", PK_HELLO_RSP_CMD_HELLO_RSP_name, PK_HELLO_RSP_CMD_HELLO_RSP_value)
	proto.RegisterType((*PK_HELLO_REQ)(nil), "hellopb.PK_HELLO_REQ")
	proto.RegisterType((*PK_HELLO_RSP)(nil), "hellopb.PK_HELLO_RSP")
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce) }

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x07, 0x73, 0x0a, 0x92, 0x94, 0x7c, 0xb8,
	0x78, 0x02, 0xbc, 0xe3, 0x3d, 0x5c, 0x7d, 0x7c, 0xfc, 0xe3, 0x83, 0x5c, 0x03, 0x85, 0x84, 0xb8,
	0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x0d,
	0x2e, 0x5e, 0x67, 0x5f, 0x17, 0x24, 0x45, 0xdc, 0x5c, 0xec, 0xa1, 0x7e, 0xde, 0x7e, 0xfe, 0xe1,
	0x7e, 0x02, 0x0c, 0x42, 0x5c, 0x5c, 0xcc, 0xce, 0xbe, 0x2e, 0x02, 0x8d, 0x0d, 0x6b, 0x02, 0x94,
	0x02, 0x90, 0x4d, 0x0b, 0x0e, 0x10, 0x12, 0xe3, 0x62, 0x4b, 0x2d, 0x2a, 0xca, 0x2d, 0x4e, 0x87,
	0x9a, 0x07, 0xe5, 0xa1, 0x99, 0x18, 0x1c, 0x80, 0xc3, 0xc4, 0x15, 0x11, 0x49, 0x6c, 0x60, 0xf7,
	0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x74, 0x87, 0x02, 0xdb, 0xbe, 0x00, 0x00, 0x00,
}
